import { PostgreSqlContainer, type StartedPostgreSqlContainer } from '@testcontainers/postgresql';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { join } from 'node:path';

declare global {
  var postgresContainer: StartedPostgreSqlContainer | undefined;
}

/**
 * Starts one PostgreSQL container for the whole suite (ADR-0007) and applies
 * the migrations generated by drizzle-kit, as in a real deployment. Tests
 * read its URL from `TEST_DATABASE_URL`.
 */
export default async function globalSetup(
  _globalConfig: unknown,
  projectConfig: { readonly rootDir: string },
): Promise<void> {
  // Same major version as `compose.yaml`.
  const container = await new PostgreSqlContainer('postgres:16-alpine').start();
  const db = drizzle({ connection: container.getConnectionUri() });
  try {
    await migrate(db, { migrationsFolder: join(projectConfig.rootDir, 'drizzle') });
  } finally {
    await db.$client.end();
  }
  globalThis.postgresContainer = container;
  process.env.TEST_DATABASE_URL = container.getConnectionUri();
}
