import { drizzleAdapter } from '@better-auth/drizzle-adapter/relations-v2';
import { betterAuth } from 'better-auth';
import type { FastifyBaseLogger } from 'fastify';

import type { Db } from '#/shared/db/client.js';
import { schema } from '#/shared/db/schema.js';

/** Prefix under which `app.ts` mounts the auth module. */
export const AUTH_BASE_PATH = '/auth';

export interface AuthConfig {
  readonly db: Db;
  readonly secret: string;
  /** Public origin of the application, without a path. */
  readonly baseUrl: string;
  readonly logger: FastifyBaseLogger;
}

/**
 * BetterAuth instance in its default configuration (ADR-0003): session
 * persisted in the database, no JWT plugin nor refresh token, default scrypt
 * hashing.
 *
 * Routes exposed under `/auth` (full list in the BetterAuth docs):
 * `POST /sign-up/email` creates the parent account and opens its session,
 * `POST /sign-in/email` opens a session, `POST /sign-out` revokes it,
 * `GET /get-session` returns the current session.
 *
 * Error responses carry BetterAuth's English `message` and a stable `code`
 * (e.g. `INVALID_EMAIL_OR_PASSWORD`): the client maps the code to its own
 * display copy.
 */
export function createAuth({ db, secret, baseUrl, logger }: AuthConfig) {
  return betterAuth({
    appName: 'Pousse',
    secret,
    baseURL: baseUrl,
    basePath: AUTH_BASE_PATH,
    database: drizzleAdapter(db, { provider: 'pg', schema }),
    emailAndPassword: { enabled: true },
    user: {
      // The `user` table stands in for PARENT (ADR-0003). First and last
      // names are optional at sign-up: the mobile sign-up screen only asks
      // for an email and a password.
      additionalFields: {
        firstName: { type: 'string', required: false },
        lastName: { type: 'string', required: false },
      },
    },
    advanced: {
      // UUID identifiers, as in the logical model; generated by PostgreSQL
      // (`defaultRandom()` in the schema).
      database: { generateId: 'uuid' },
    },
    telemetry: { enabled: false },
    // Logging goes through Pino, already embedded by Fastify (ADR-0001).
    logger: {
      log: (level, message, ...args) => {
        logger[level]({ args }, `[better-auth] ${message}`);
      },
    },
  });
}

export type Auth = ReturnType<typeof createAuth>;
